#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib.sh
source "$SCRIPT_DIR/lib.sh"
load_config
require_config WORKER_SSH WORKER_CHECKOUT MODEL_DIR WORKER_MODEL_DIR \
  HEAD_ROCE_IP WORKER_ROCE_IP HEAD_NCCL_SOCKET_IFNAME HEAD_NCCL_IB_HCA \
  HEAD_NCCL_IB_GID_INDEX WORKER_NCCL_SOCKET_IFNAME WORKER_NCCL_IB_HCA \
  WORKER_NCCL_IB_GID_INDEX MASTER_PORT

echo "Stopping head..."
COMPOSE_PROJECT_NAME=dual-spark MODEL_DIR="$MODEL_DIR" NODE_RANK=0 HEADLESS='' \
MASTER_ADDR="$HEAD_ROCE_IP" MASTER_PORT="$MASTER_PORT" VLLM_HOST_IP="$HEAD_ROCE_IP" \
NCCL_SOCKET_IFNAME="$HEAD_NCCL_SOCKET_IFNAME" NCCL_IB_HCA="$HEAD_NCCL_IB_HCA" \
NCCL_IB_GID_INDEX="$HEAD_NCCL_IB_GID_INDEX" \
docker compose --env-file "$ENV_FILE" \
  -f "$ROOT_DIR/docker-compose.dspark.yml" down || true

echo "Stopping worker..."
ssh "$WORKER_SSH" "cd '$WORKER_CHECKOUT' && \
  COMPOSE_PROJECT_NAME=dual-spark MODEL_DIR='$WORKER_MODEL_DIR' NODE_RANK=1 HEADLESS=1 \
  MASTER_ADDR='$HEAD_ROCE_IP' MASTER_PORT='$MASTER_PORT' VLLM_HOST_IP='$WORKER_ROCE_IP' \
  NCCL_SOCKET_IFNAME='$WORKER_NCCL_SOCKET_IFNAME' NCCL_IB_HCA='$WORKER_NCCL_IB_HCA' \
  NCCL_IB_GID_INDEX='$WORKER_NCCL_IB_GID_INDEX' \
  docker compose --env-file .env -f docker-compose.dspark.yml down" || true
